image:
  file: .gitpod.Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6363
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public
